### ISSUE TITLE
Non-Docker install instructions

### ISSUE THREAD

**Issue by Marenz** [cotoami/cotoami#133]
It would be nice if there were non-docker install & use instructions to run it directly without docker

**Comment by devsecur** [comment]
isn't this documented by the docker and docker-compose files itself?

**Comment by marubinotto** [comment]
> isn't this documented by the docker and docker-compose files itself?

Yeah, that's kind of true, but it's not easy to install and launch Cotoami without Docker because it depends on serveral backend services in addition to a relational database. To mitigate the difficulty for personal use, I'm thinking about providing an all-in-one Docker image that includes all the dependencies.

Anyway, as for Cotoami server, Docker is the default installation method for now. So I'm going to close this issue.
