### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by devsecur** [cotoami/cotoami#154]
I'm trying to deploy a test instance to my kubernetes cluster. In the `deploy-develop.sh` script, I saw some kubectl, but i didn't found a yaml file yet. 

Is there any yaml file or helm chart to simplify kubernetes deployments yet? Otherwise, I could convert the docker-compose and offer an example on my own...

**Comment by marubinotto** [comment]
As you noticed, https://cotoa.me was managed on a k8s cluster before (it was migrated to Heroku due to a financial reason). The manifest files are here: https://github.com/cotoami/cotoami-infra/tree/master/k8s/prod It'd be a little bit outdated, but it should work with a little modification (newly added application env values are missing).
